olio/acetobugs/urls.py
from django.urls import path
from olio.acetobugs.views import ProblemsView, ProblemChangeView

app_name = 'acetobugs'

urlpatterns = [
    path('',  ProblemsView.as_view(), name='problems'),
    path('problem/<int:pk>/', ProblemChangeView.as_view(), name='problem')
]

olio/urls.py
from django.urls import path, include
from django.contrib import admin
from olio.acetomed.views import index as patient_index

# TODO make acetomed app's URLs relative
urlpatterns = [
    path('', patient_index),
    path('admin/', admin.site.urls),
    path('acetomed/', include('olio.acetomed.urls')),
    path('purchase/', include('olio.purchase.urls')),
    path('acetobugs/', include('olio.acetobugs.urls')),
]

olio/acetobugs/models.py
from django.db import models
from django.utils.datetime_safe import strftime


class AcetoMandant(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)

    def __str__(self):
        return '{}, {}'.format(self.lastname, self.firstname)

    class Meta:
        verbose_name = 'Aceto-Mandant'
        verbose_name_plural = 'Aceto-Mandanten'


class Problem(models.Model):
    aceto_mandant = models.ForeignKey(AcetoMandant,
                                     default=716,
                                     on_delete=models.PROTECT)
    aceto_ticketnumber = models.IntegerField(verbose_name='Hilfefall-Nr.')

    title = models.CharField(max_length=50, verbose_name='Titel')
    description = models.TextField(verbose_name='Beschreibung')
    created = models.DateTimeField(auto_now=True, verbose_name='Erstellt am')
    solved = models.BooleanField(verbose_name='Problem wurde gelöst')

    class Meta:
        verbose_name = 'Problem'
        verbose_name_plural = 'Probleme'

    def __str__(self):
        return self.title


class Call(models.Model):
    timestamp = models.DateTimeField(editable=True,
                                     verbose_name='Anrufzeit')
    reached = models.BooleanField(default=False,
                                  verbose_name="ACETO am Telefon erreicht")
    problems = models.ManyToManyField(Problem,
                                      verbose_name='Probleme',
                                      related_name='calls')
    description = models.TextField(blank=True,
                                   verbose_name='Zusammenfassung des Anrufs')

    def __str__(self):
        return '{}'.format(strftime(self.timestamp, '%d.%m.%Y %M:%S'))

    class Meta:
        verbose_name = 'Anruf'
        verbose_name_plural = 'Anrufe'

olio/acetobugs/views.py
from django.views.generic import TemplateView, ListView
from olio.acetobugs.models import Problem


class ProblemsView(ListView):
    model = Problem

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['problems'] = Problem.objects.all()
        return context


class ProblemChangeView(ListView):
    model = Problem

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['problem'] = Problem.objects.get(pk=kwargs['pk'])
        return context

olio/acetobugs/templates/acetobugs/problem_change.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ problem.title }} ({{ problem.aceto_mandant.id }}/{{ problem.aceto_ticketnumber }})</h2>
<div class="">
    <p>{{ problem.description }}</p>
    <h4>Anrufe</h4>
    <div class="list-group">
        {% for call in problem.calls.all %}
        <a href="#" class="list-class-item">{{ call.id }}
        <span class="badge">tes</span></a>
        {% empty %}
        keine Anrufe bisher.
        {% endfor %}
    </div>
</div>
{% endblock content %}

olio/acetobugs/templates/acetobugs/problem_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Gemeldete ACETOmed - Probleme</h2>
    <div class="list-group">
        {% for problem in problems %}
            <a class="list-group-item{% if   problem.solved %} disabled{% endif %}" href="{% url 'acetobugs:problem' problem.id %}">
                <span class="badge">{{ problem.aceto_mandant.id }}/{{ problem.aceto_ticketnumber }}</span>
                <h4 class="list-group-item-heading">{{ problem.title }}</h4>
                <p class="list-group-item-text">{{ problem.description }}</p>
            </a>

        {% endfor %}
    </div>
{% endblock content %}