olio/acetomed/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.urls import path, include

import olio.acetomed.views as views
from olio.acetomed.views import PatientSearchView, NotSentVUsView, ProblemsView

app_name = 'acetomed'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pat_id>/', views.file, name='detail'),
    path('search/<str:patient_search_string>/', login_required(PatientSearchView.as_view()), name="patientsearch"),
    path('search/', login_required(PatientSearchView.as_view()), name="patientsearch"),
    path('problems/', login_required(ProblemsView.as_view()), name='problems'),
    path('problems/notsentvus', login_required(NotSentVUsView.as_view()), name="notsentvus"),
    path('clinical_reports/', login_required(
        views.UnreadClinicalFindingsView.as_view()), name='clinical_reports'),
]

olio/urls.py
from django.urls import path, include
from django.contrib import admin
from olio.acetomed.views import index as patient_index

# TODO make acetomed app's URLs relative
urlpatterns = [
    path('', patient_index),
    path('admin/', admin.site.urls),
    path('acetomed/', include('olio.acetomed.urls')),
    path('purchase/', include('olio.purchase.urls')),
    path('acetobugs/', include('olio.acetobugs.urls')),
]

olio/acetomed/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

from django.db import models
from .fields import Base64CharField, Base64TextField
from enum import Enum

__VERSION__ = (1,4,274)

Fachgebiete = {
    1: 'Allgemeinmedizin',
    # FIXME: add rest
}


class AbrechnungBuffer(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    typ = models.IntegerField(db_column='TYP', blank=True, null=True)
    mandand_id = models.IntegerField(db_column='MANDAND_ID', blank=True, null=True)
    abrechnungsstellekennung = models.CharField(db_column='AbrechnungsstelleKennung', max_length=255, blank=True, null=True)
    abrechnungskassenkennungen = models.CharField(db_column='AbrechnungsKassenKennungen', max_length=255, blank=True, null=True)
    abrechnungskassentypen = models.CharField(db_column='AbrechnungsKassenTypen', max_length=255, blank=True, null=True)
    erstellung = models.DateTimeField(db_column='Erstellung', blank=True, null=True)
    zeitraumjahr = models.IntegerField(db_column='ZeitraumJahr', blank=True, null=True)
    zeitraumkennung = models.IntegerField(db_column='ZeitraumKennung', blank=True, null=True)
    datum_start = models.DateField(db_column='DATUM_START', blank=True, null=True)
    datum_ende = models.DateField(db_column='DATUM_ENDE', blank=True, null=True)
    text = models.TextField(db_column='Text', blank=True, null=True)
    zeile_lock = models.CharField(db_column='ZEILE_LOCK', max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ABRECHNUNG_BUFFER'


class AbrechnungHl7Zuordnung(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    hl7_segment = models.CharField(db_column='HL7_SEGMENT', max_length=50, blank=True, null=True)
    hl7_ergebnis_typ = models.CharField(db_column='HL7_ERGEBNIS_TYP', max_length=50, blank=True, null=True)
    hl7_ergebnis_beschreibung = models.CharField(db_column='HL7_ERGEBNIS_BESCHREIBUNG', max_length=255, blank=True, null=True)
    hl7_ergebnis_identifier = models.CharField(db_column='HL7_ERGEBNIS_IDENTIFIER', max_length=50, blank=True, null=True)
    kasse = models.CharField(db_column='KASSE', max_length=50, blank=True, null=True)
    ziffer = models.CharField(db_column='ZIFFER', max_length=50, blank=True, null=True)
    ziffer_anzahl_faktor = models.FloatField(db_column='ZIFFER_ANZAHL_FAKTOR')

    class Meta:
        managed = False
        db_table = 'ABRECHNUNG_HL7_ZUORDNUNG'


class AcetoEinstellungen(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    name = models.CharField(db_column='NAME', max_length=255, blank=True, null=True)
    wert = models.TextField(db_column='WERT', blank=True, null=True)
    werteliste = models.CharField(db_column='WERTELISTE', max_length=255, blank=True, null=True)
    status = models.IntegerField(db_column='STATUS')
    protokoll = models.TextField(db_column='PROTOKOLL', blank=True, null=True)
    zeile_lock = models.CharField(db_column='ZEILE_LOCK', max_length=255, blank=True, null=True)
    letzte_aenderung = models.DateTimeField(db_column='LETZTE_AENDERUNG', blank=True, null=True)
    typ = models.IntegerField(db_column='TYP')
    bereich = models.CharField(db_column='BEREICH', max_length=255, blank=True, null=True)
    fremd_id = models.IntegerField(db_column='FREMD_ID')
    mandant_id = models.IntegerField(db_column='MANDANT_ID', blank=True, null=True)
    # on_delete=models.PROTECT because of ReadOnly DB
    benutzer = models.ForeignKey("Benutzer", db_column='BENUTZER_ID', blank=True, null=True, on_delete=models.PROTECT)
    rechner_name = models.CharField(db_column='RECHNER_NAME', max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ACETO_EINSTELLUNGEN'


class AcetoKontakt(models.Model):
    web_id = models.IntegerField(db_column='WEB_ID', primary_key=True)
    datum = models.DateTimeField(db_column='DATUM', blank=True, null=True)
    xml = models.TextField(db_column='XML')
    patient_id = models.IntegerField(db_column='PATIENT_ID', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ACETO_KONTAKT'


class Adresse(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    typ = models.IntegerField(db_column='TYP')
    strasse = models.CharField(db_column='STRASSE', max_length=255, blank=True, null=True)
    hausnummer = models.CharField(db_column='HAUSNUMMER', max_length=255, blank=True, null=True)
    adresszusatz = models.CharField(db_column='ADRESSZUSATZ', max_length=255, blank=True, null=True)
    plz = models.CharField(db_column='PLZ', max_length=255, blank=True, null=True)
    ort = models.CharField(db_column='ORT', max_length=255, blank=True, null=True)
    bundesland = models.CharField(db_column='BUNDESLAND', max_length=255, blank=True, null=True)
    land_code = models.CharField(db_column='LAND_CODE', max_length=255, blank=True, null=True)
    postfach = models.CharField(db_column='POSTFACH', max_length=255, blank=True, null=True)
    postfach_plz = models.CharField(db_column='POSTFACH_PLZ', max_length=255, blank=True, null=True)
    postfach_ort = models.CharField(db_column='POSTFACH_ORT', max_length=255, blank=True, null=True)
    postfach_land_code = models.CharField(db_column='POSTFACH_LAND_CODE', max_length=255, blank=True, null=True)
    letzte_aenderung = models.DateTimeField(db_column='LETZTE_AENDERUNG', blank=True, null=True)
    zeile_lock = models.CharField(db_column='ZEILE_LOCK', max_length=255, blank=True, null=True)
    status = models.IntegerField(db_column='STATUS', blank=True, null=True)
    tabelle = models.IntegerField(db_column='TABELLE')

    class Meta:
        managed = False
        db_table = 'ADRESSE'
        verbose_name = "Adresse"
        verbose_name_plural = "Adressen"

    def __str__(self):
        return "{} {}, {} {}".format(
            self.strasse,
            self.hausnummer,
            self.plz,
            self.ort)


class Allergene(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    typ = models.IntegerField(db_column='TYP', blank=True, null=True)
    kuerzel = models.CharField(db_column='KUERZEL', max_length=255, blank=True, null=True)
    bezeichnung = models.CharField(db_column='BEZEICHNUNG', max_length=255, blank=True, null=True)
    beschreibung = models.TextField(db_column='BESCHREIBUNG', blank=True, null=True)
    gruppe = models.IntegerField(db_column='GRUPPE', blank=True, null=True)
    mandanten = models.CharField(db_column='MANDANTEN', max_length=255, blank=True, null=True)
    bearbeiter = models.CharField(db_column='BEARBEITER', max_length=50, blank=True, null=True)
    zeile_lock = models.CharField(db_column='ZEILE_LOCK', max_length=255, blank=True, null=True)
    letzte_aenderung = models.DateTimeField(db_column='LETZTE_AENDERUNG', blank=True, null=True)
    protokoll = models.TextField(db_column='PROTOKOLL', blank=True, null=True)
    prick = models.IntegerField(db_column='PRICK', blank=True, null=True)
    prick_prick = models.IntegerField(db_column='PRICK_PRICK', blank=True, null=True)
    epicutan = models.IntegerField(db_column='EPICUTAN', blank=True, null=True)
    intracutan = models.IntegerField(db_column='INTRACUTAN', blank=True, null=True)
    scratch = models.IntegerField(db_column='SCRATCH', blank=True, null=True)
    bluttest_intern = models.IntegerField(db_column='BLUTTEST_INTERN', blank=True, null=True)
    bluttest_extern = models.IntegerField(db_column='BLUTTEST_EXTERN', blank=True, null=True)
    impfung = models.IntegerField(db_column='IMPFUNG', blank=True, null=True)
    typ_profil = models.CharField(db_column='TYP_PROFIL', max_length=255, blank=True, null=True)
    profil_parameter_ids = models.CharField(db_column='PROFIL_PARAMETER_IDS', max_length=255, blank=True, null=True)
    favorit = models.IntegerField(db_column='FAVORIT', blank=True, null=True)
    favorit_position = models.IntegerField(db_column='FAVORIT_POSITION', blank=True, null=True)
    individuell = models.IntegerField(db_column='INDIVIDUELL', blank=True, null=True)
    labor_auftragparameter_codeimlabor = models.CharField(db_column='LABOR_AUFTRAGPARAMETER_CODEIMLABOR', max_length=255, blank=True, null=True)
    laborauftrag_zuweiser_id = models.IntegerField(db_column='LABORAUFTRAG_ZUWEISER_ID', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ALLERGENE'
        unique_together = (('kuerzel', 'gruppe'),)
        verbose_name_plural = "Allergene"

    def __str__(self):
        return self.bezeichnung


class Allergentest(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    allergentestdokuid = models.IntegerField(db_column='ALLERGENTESTDOKUID', unique=True, blank=True, null=True)
    gesamtige = models.IntegerField(db_column='GESAMTIGE', blank=True, null=True)
    start_zeit = models.DateTimeField(db_column='START_ZEIT', blank=True, null=True)
    end_zeit = models.DateTimeField(db_column='END_ZEIT', blank=True, null=True)
    timer_typ = models.IntegerField(db_column='TIMER_TYP', blank=True, null=True)
    status = models.IntegerField(db_column='STATUS', blank=True, null=True)
    bemerkung = models.CharField(db_column='BEMERKUNG', max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ALLERGENTEST'


class Allergentestwert(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    allergentestdokuid = models.IntegerField(db_column='ALLERGENTESTDOKUID', blank=True, null=True)

olio/acetomed/views.py
from django.shortcuts import render
from django.http import Http404

from .models import Patient, Dokumentation, Medikament, Combo
from django.contrib import messages
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required


@login_required(login_url="/admin/login")
def index(request):
    return render(request, "acetomed/index.html")


@login_required(login_url="/admin/login")
def file(request, pat_id):
    try:
        p = Patient.objects.get(pk=pat_id)
    except Patient.DoesNotExist:
        messages.ERROR(request,
                       "Der Patient mit der ID {} wurde nicht gefunden.".
                       format(pat_id))
        return render(request, "")

    if p.geschlecht == 1:
        sex = "male"
    elif p.geschlecht == 2:
        sex = "female"
    else:
        sex = "unknown"

    kennzeichen = []
    for i in range(10):
        kzname = 'kennzeichen{}'.format(i+1)
        kennung = getattr(p.patientzusatz, kzname)
        kz = (
            kennung,
            Combo.objects.filter(name=kzname, kennung=kennung).first()
              )
        kennzeichen.append(kz)

    return render(request, "acetomed/patients/file.html", {
        "patient": p,
        "kennzeichen": kennzeichen,
        "doku": p.dokumentation_set.all().exclude(
                    status=Dokumentation.Status.GELOESCHT.value
                ).order_by("-untersuchung_nr", "-datum"),

        # FIXME: offensichtlich ist patient_id nicht sinnvoll verknüpft.
        "medikamente": p.medikament_set.filter(typ="DM"),
        "diagnosen": p.diagnose_set.filter(typ="DD"),
        "sex": sex,
        "medizin": p.patientmedizin,
        })


class PatientSearchView(ListView):
    model = Patient
    context_object_name = "patients"
    template_name = "acetomed/patients/patient_list.html"

    def get_queryset(self):
        searchstring = self.request.GET.get("patient_search_string", "").strip()
        if not searchstring:
            messages.error(self.request,
                           "Gesucht werden kann mittels 'Name', oder "
                           "'Name, Vorname', "
                           "oder Teilen davon, z.B findet 'mus,m' alle"
                           " Personen, deren "
                           "Nachname mit 'Mus' und deren Vorname mit "
                           "'M' beginnen. Groß- Kleinschreibung "
                           "wird ignoriert. Es kann auch eine SVNR "
                           "als Suchparameter angegeben werden, z.B. '1234'")
            return []
        else:
            try:
                # try to parse searchstring as SVNR
                svnr = int(searchstring)
                return Patient.objects.filter(
                    versicherungsnr__startswith=str(svnr))
            except ValueError:
                # try to parse searchstring as "lastname,firstname"
                if "," in searchstring:
                    if searchstring.count(",") != 1:
                        raise Http404("Fehler in Sucheingabe")

                    lastname, firstname = searchstring.split(",")
                    return Patient.objects.filter(
                        name__istartswith=lastname,
                        vorname__istartswith=firstname)
                else:
                    return Patient.objects.filter(
                            name__istartswith=searchstring)


class MedicationSearchView(ListView):
    model = Medikament
    context_object_name = "medikamente"
    #template_name = "acetomed/patient_list.html"

    def get_queryset(self):
        searchstring = self.request.GET.get("searchstring", "").strip()
        if not searchstring:
            messages.error(self.request,
                           "Es kann nach Medimanentennamen gesucht werden, "
                           "so wie sie in der Kartei gespeichert sind. "
                           "Groß- Kleinschreibung "
                           "wird ignoriert.")
            return []
        else:
            try:
                drugname = searchstring.strip()
                return Medikament.objects.filter(
                        patient_id=1,
                        medikament__istartswith=drugname)
            except ValueError:
                return []


class ProblemsView(TemplateView):
    template_name = "acetomed/problems.html"


class NotSentVUsView(ListView):
    """Lists all VUs that have not been sent."""
    template_name = "acetomed/dokumentation_list_notsentvus.html"
    model = Dokumentation
    queryset = Dokumentation.objects.filter(typ="AT_F_VU2017_ALLG") \
                .exclude(status=Dokumentation.Status.VERSENDET.value) \
                .exclude(status=Dokumentation.Status.GELOESCHT.value) \
                .exclude(status=Dokumentation.Status.STORNIERT.value) \
                .order_by("datum")



class UnreadClinicalFindingsView(ListView):
    """Lists all new, unread clinical findings."""
    model = Dokumentation
    context_object_name = "dokumentation"
    template_name = "acetomed/dokumentation_list_unreadclinfindings.html"
    queryset = Dokumentation.objects.select_related('patient').filter(
        typ__in=["Laborbefund", "Fremdbefund"]).exclude(status=Dokumentation.Status.GELOESCHT.value)

    #def get_queryset(self):
#        return Dokumentation.objects.filter(typ__in=["Laborbefund", "Fremdbefund"]) \
#                .exclude(status=Dokumentation.Status.VERSENDET.value) \
#                .exclude(status=Dokumentation.Status.GELOESCHT.value) \
#                .exclude(status=Dokumentation.Status.STORNIERT.value)

olio/acetomed/templates/acetomed/patients/file.html
{% extends "acetomed/base.html" %}

{% block header %}
<div class="header sex-{{sex}}">
  {% if medizin.cave %}
  <div class="cave pull-right">
    {{ medizin.cave|default:"" }}
  </div>
  {% endif %}
  {% if medizin.info %}
  <div class="info pull-right">
    {{ medizin.info|default:"" }}
  </div>
  {% endif %}

  {% for kz in kennzeichen %}
    <a href="#" class="badge kennzeichen kennzeichen-{{ forloop.counter }}{% if kz.0 != -1 %}-{{ kz.0 }}{% endif %}">
      {% if kz.1 %}
        {{kz.1}}
      {% endif %}
    </a>
  {% endfor %}




  <h2 class="patient-name">{{ patient.name }}, {{ patient.vorname }} ({{ patient.gebdatum| date:"d.m.Y" }})</h2>

  <div class="header-item" style="background:grey;color:white;">
    ID: {{ patient.id }}
  </div>

  <div class="header-item">
    <span class="glyphicon glyphicon-credit-card"></span>
    SVNR: {{ patient.versicherungsnr }}
  </div>

  <div class="header-item adresse">
    <span class="glyphicon glyphicon-envelope"></span>
    {{ patient.strasse }} {{ patient.hausnummer }}, {{ patient.plz }} {{ patient.ort }}
  </div>

  <div class="header-item phone">
    <span class="glyphicon glyphicon-phone"></span>
    {{ patient.telefon }}
  </div>
</div>
{% endblock header %}


{% block sidebar %}
  <h4>Diagnosen</h4>
  {% for d in diagnosen %}
    <div class="doku_typ_diagnose">{{ d.diagnose_text }} ({{ d.status }})</div>
  {% endfor %}
  <h4>Medikamente</h4>
  {% for m in medikamente %}
    <div>{{ m.medikament }}</div>
  {% endfor %}
{% endblock sidebar %}


{% block content %}
  <table class="table-condensed table-hover">
    {% for line in doku %}
      {% if line.typ|lower == "untersuchung" %}
        <tr class="doku_typ_untersuchung" data-toggle="tooltip"
          title="Untersuchung-ID: FIXME">
          <td class="col-sm-1 date">{{ line.datum|date:"d.m.Y" }}</td>
      {% else %}
        <tr>
          <td class="col-sm-1 date"></td>
      {% endif %}
          <td class="col-sm-8 doku_typ_{{ line.typ|lower }} status-{{ line.status }}">
          {% if line.status == 99 %}
          <del><span data-toggle="tooltip"
            title="gelöscht">{{ line.doku_text }}</span></del>
          {% elif line.status == 90 %}
            <span data-toggle="tooltip"
            title="bereits abgerechnet">{{ line.doku_text }}</span>
          {% else %}
            {{ line.doku_text|striptags }}
          {% endif %}
          </td>
          <td class="col-sm-1">{{line.status}}</td>
          <td class="col-sm-1" data-toggle="tooltip"
            title="Zuletzt geändert am {{line.letzte_aenderung_datum }} um {{ line.letzte_aenderung_uhrzeit }}">{{ line.bearbeiter }}</td>
        </tr>
    {% endfor %}
  </table>
{% endblock content %}

olio/acetomed/templates/acetomed/patients/index.html
{% extends "acetomed/base.html" %}

olio/acetomed/templates/acetomed/patients/patient_list.html
{% extends "acetomed/base.html" %}

{% block content %}
<div class="table-responsive">
  <table class="list-group table table-hover">
    {% for patient in patients %}
      <tr id="patient-id-{{ p.id }}">
        <td><span class="badge">{{ patient.titel|default:"" }}</span></td>
        <td><a href="{% url 'acetomed:detail' patient.id %}"
               data-toggle="tooltip"
               title="ID: {{ patient.id }}, SVNR: {{ patient.versicherungsnr }}">{{ patient.name }}</a></td>
        <td>{{ patient.vorname }}</td>
        <td>{{ patient.gebdatum | date:"d.m.Y" }}</td>
      </tr>
    {% empty %}
      <tr>
      <td>Keine Patienten mit den Suchkriterien gefunden</td>
      </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

olio/acetomed/templates/acetomed/patients/search.html
{% load bootstrap3 %}

{% block search %}
    <form id="patientsearchform" class="form-inline navbar-form navbar-right" action="{% url 'acetomed:patientsearch' %}" method="GET" accept-charset="utf-8">
        {% csrf_token %}
        <div class="form-group">
          <input name="patient_search_string" id="patient_search_string" type="search" class="form-control mr-sm-2" placeholder="Vorname, Nachname">
        </div>
        {% buttons %}
          <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span> Suche</button>
        {% endbuttons %}
    </form>
{% endblock %}